### ISSUE TITLE
Improve Error Reporting

### ISSUE THREAD

**Issue by 7h3Rabbit** [Webperf-se/webperf_core#270]
Make it easier to find what went wrong AND improve the format so we get better issues, hopefully resulting in faster error identification

**Comment by 7h3Rabbit** [comment]
We will now write a `failures.log` file into your webperf_core folder with following info and format for every error occuring:

```
###############################################
# Information:
DateTime: 2024-02-15 14:52:24
Url: https://are.se
Language Code: en
Test Type(s): 25
Show Reviews: True
###############################################
# Configuration (from config.py):
useragent: Mozilla/5.0 (compatible; Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36 Edg/88.0.705.56
http_request_timeout: 60
webbkoll_sleep: 20
css_review_group_errors: True
review_show_improvements_only: False
ylt_use_api: False
lighthouse_use_api: False
sitespeed_use_docker: False
sitespeed_iterations: 2
locales: locales
cache_when_possible: True
cache_time_delta: 30 days, 0:00:00
software_use_stealth: True
software_use_detailed_report: True
software_browser: chrome
###############################################
Traceback (most recent call last):
  File "C:\Users\WebPerf\Documents\Projects\webperf_core\utils.py", line 68, in test
    the_test_result = run_test(_, langCode, website)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\WebPerf\Documents\Projects\webperf_core\tests\software.py", line 1564, in run_test
    (rating, result_dict) = get_rating_from_sitespeed(url, _local, _)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\WebPerf\Documents\Projects\webperf_core\tests\software.py", line 125, in get_rating_from_sitespeed
    data = enrich_data(data, origin_domain, result_folder_name, rules)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\WebPerf\Documents\Projects\webperf_core\tests\software.py", line 541, in enrich_data
    enrich_versions(item)
  File "C:\Users\WebPerf\Documents\Projects\webperf_core\tests\software.py", line 779, in enrich_versions
    elif tmp_version > version:
         ^^^^^^^^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'Version' and 'str'
###############################################
```

**Comment by 7h3Rabbit** [comment]
Solved and closed
