### ISSUE TITLE
Stylelint CSS test error on Google Fonts

### ISSUE THREAD

**Issue by krompaco** [Webperf-se/webperf_core#761]
### URL

https://www.herlitz.io

### Webperf_core version

2024.12.2

### What environment are you running?

- [ ] Using GitHub Actions
- [X] Using Docker Image from Dock Hub
- [ ] Local machine
- [ ] Other, please describe your environment in How to reproduce.

### Has anyone else reported it already?

- [X] No, there are no other issues related to this in [Issues](https://github.com/Webperf-se/webperf_core/issues).

### Expected Behavior

No result output is shown.

### Actual Behavior.

A FileNotFoundError: [Errno 2] is thrown.

### How to reproduce

```shell
python3 default.py -r -t 27 -u https://www.herlitz.io
```

### Log output

```shell
sitespeedio@f2c082b5ea9c:/usr/src/runner$ python3 default.py -r -t 27 -u https://www.herlitz.io
###############################################
# Testing website https://www.herlitz.io

## Test: 27 - CSS

Started: 2024-12-09 12:11:28
Finished: 2024-12-09 12:11:53

###############################################
# Version information (from packages.json)
Version: 2024.12.2
Dependencies:
- lighthouse v12.2.2
- pa11y v8.0.0
- sitespeed.io v35.7.0
- stylelint v16.10.0
- vnu-jar v23.4.11
- yellowlabtools v3.0.1

###############################################
# Information:
DateTime: 2024-12-09 12:11:53
Url: https://www.herlitz.io
Test Type(s): 27
###############################################
# Used Configuration:
general.cache.use: True
general.cache.max-age: 60
tests.software.advisory.path:
general.language: en
general.review.show: True
general.review.improve-only: False
tests.sitespeed.xvfb: False
tests.sitespeed.docker.use: False
tests.sitespeed.timeout: 300
general.request.timeout: 60
###############################################
Traceback (most recent call last):
  File "/usr/src/runner/helpers/test_helper.py", line 100, in test
    the_test_result = run_test(global_translation, site[1])
  File "/usr/src/runner/tests/css_linting.py", line 57, in run_test
    tmp_all_link_resources, tmp_rating = handle_html_markup_entry(
                                         ~~~~~~~~~~~~~~~~~~~~~~~~^
        html_entry,
        ^^^^^^^^^^^
    ...<2 lines>...
        local_translation,
        ^^^^^^^^^^^^^^^^^^
        result_dict)
        ^^^^^^^^^^^^
  File "/usr/src/runner/tests/css_linting.py", line 159, in handle_html_markup_entry
    (link_resources, errors) = get_errors_for_link_tags(html, url)
                               ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/usr/src/runner/tests/css_linting.py", line 424, in get_errors_for_link_tags
    results += get_errors_for_url(
               ~~~~~~~~~~~~~~~~~~^
        'css',
        ^^^^^^
        resource_url)
        ^^^^^^^^^^^^^
  File "/usr/src/runner/tests/lint_base.py", line 19, in get_errors_for_url
    return get_errors(test_type, params)
  File "/usr/src/runner/tests/lint_base.py", line 98, in get_errors
    with open(lint_file_path, encoding='utf-8') as json_input_file:
         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/usr/src/runner/cache/fonts.googleapis.com/27126476c38bead962a1224c48b250af1b4269996388ca802d047c0c715855979240497a0969c08623176942d8d041b42a002d4e07533409fcad0c5f1e053416.txt.utf-8.cache.css-lint.json'
```

**Comment by 7h3Rabbit** [comment]
Resolved by better handling when creating cache keys.
